/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountForm: typeof import('./src/components/AccountForm.vue')['default']
    AccountList: typeof import('./src/components/AccountList.vue')['default']
    AddExpenseDialog: typeof import('./src/components/AddExpenseDialog.vue')['default']
    AdjustBalanceDialog: typeof import('./src/components/AdjustBalanceDialog.vue')['default']
    AdjustBalanceForm: typeof import('./src/components/AdjustBalanceForm.vue')['default']
    BudgetDialog: typeof import('./src/components/BudgetDialog.vue')['default']
    CategoryAnalysis: typeof import('./src/components/CategoryAnalysis.vue')['default']
    CategoryForm: typeof import('./src/components/CategoryForm.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    ExpenseForm: typeof import('./src/components/ExpenseForm.vue')['default']
    ExpenseList: typeof import('./src/components/ExpenseList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ReportOverview: typeof import('./src/components/ReportOverview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagForm: typeof import('./src/components/TagForm.vue')['default']
    TagList: typeof import('./src/components/TagList.vue')['default']
    TransferDialog: typeof import('./src/components/TransferDialog.vue')['default']
    TransferForm: typeof import('./src/components/TransferForm.vue')['default']
    TrendAnalysis: typeof import('./src/components/TrendAnalysis.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
