/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountForm: typeof import('./components/AccountForm.vue')['default']
    AccountList: typeof import('./components/AccountList.vue')['default']
    AddExpenseDialog: typeof import('./components/AddExpenseDialog.vue')['default']
    AdjustBalanceDialog: typeof import('./components/AdjustBalanceDialog.vue')['default']
    AdjustBalanceForm: typeof import('./components/AdjustBalanceForm.vue')['default']
    BudgetDialog: typeof import('./components/BudgetDialog.vue')['default']
    CategoryAnalysis: typeof import('./components/CategoryAnalysis.vue')['default']
    CategoryForm: typeof import('./components/CategoryForm.vue')['default']
    ExpenseForm: typeof import('./components/ExpenseForm.vue')['default']
    ExpenseList: typeof import('./components/ExpenseList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ReportOverview: typeof import('./components/ReportOverview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransferDialog: typeof import('./components/TransferDialog.vue')['default']
    TransferForm: typeof import('./components/TransferForm.vue')['default']
    TrendAnalysis: typeof import('./components/TrendAnalysis.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
  }
}
